export const TASK_TYPES = {
  CONFIRM: 'confirm',
  CONDITIONAL: 'conditional',
  CONDITION: 'condition',
  ACTION: 'action',
  PROGRESS: 'progress',
  COMPLEX: 'complex',
  UPLOAD: 'upload',
} as const

export const TASK_CATEGORIES = {
  CONFIRMATION: 'confirmation',
  APPROVAL: 'approval',
  APPROVAL1: 'approval1',
  ASSIGNMENT: 'assignment',
  ASSIGNMENT1: 'assignment1',
  CONTRACT: 'contract',
  CERTIFICATE: 'certificate',
  EMAIL: 'email',
  SELECTOR: 'selector',
  INPUT: 'input',
  INVOICE: 'invoice',
  VISIT: 'visit',
  SCHEDULEA: 'schedulea',
  SCHEDULEA_ASSIGNING: 'scheduleaassigning',
  SCHEDULEA_START: 'scheduleastart',
  SCHEDULEB: 'scheduleb',
  SCHEDULEB_ASSIGN_PRODUCTS: 'schedulebassignprod',
  SCHEDULEB_START: 'schedulebstart',
  SCHEDULING: 'scheduling',
  PROGRESS_TASK: 'progress_task',
  UPLOAD: 'upload',
} as const
