/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OuWorkflowIndexRouteImport } from './routes/ou-workflow/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OuWorkflowIndexRoute = OuWorkflowIndexRouteImport.update({
  id: '/ou-workflow/',
  path: '/ou-workflow/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ou-workflow': typeof OuWorkflowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ou-workflow': typeof OuWorkflowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ou-workflow/': typeof OuWorkflowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ou-workflow'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ou-workflow'
  id: '__root__' | '/' | '/ou-workflow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OuWorkflowIndexRoute: typeof OuWorkflowIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ou-workflow/': {
      id: '/ou-workflow/'
      path: '/ou-workflow'
      fullPath: '/ou-workflow'
      preLoaderRoute: typeof OuWorkflowIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OuWorkflowIndexRoute: OuWorkflowIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
